[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
private_dao_voting = "71tbXM3A2j5pKHfjtu1LYgY8jfQWuoZtHecDu6F6EPJH"

[registry]
url = "https://api.apr.dev"

[test]
startup_wait = 30000

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 e2e.test.ts tests/**/*.ts"
